### ISSUE TITLE
Charset UTF-8 problems

### ISSUE THREAD

**Issue by 7jeanvictor** [m1geo/MediaWiki-to-WordPress#3]
I have a problem with charset UTF-8. 

I have a charset UTF-8 mediawiki.xml. When I generate a wordpress.xml using the script, my special characters (like á, ã, ç, ...) are replaced by ascii codes (weird codes).

So, my mediawiki.xml is UTF-8, the processed wordpress.xml is UTF-8, but the script read the mediawiki.xml file like charset US ASCII. How to fix this? 

Thank you for all.

**Comment by m1geo** [comment]
Hi. I expect this is a relatively easy fix. However I won't have time for a few weeks to take a look because of work, holiday and other projects. If you find a solution in the meantime, feel free to submit a pull request.

**Comment by 7jeanvictor** [comment]
Thank you for reply! I made a java app to decode it. I will share when it's done.

**Comment by twixi** [comment]
> Thank you for reply! I made a java app to decode it. I will share when it's done.

public please your app!

**Comment by 7jeanvictor** [comment]
> > Thank you for reply! I made a java app to decode it. I will share when it's done.
> 
> public please your app!

Ok, I w> > Thank you for reply! I made a java app to decode it. I will share when it's done.
> 
> public please your app!

Ok, I will. This week.

**Comment by twixi** [comment]
any news?
